---
/**:
  ros__parameters:
      # This sets the iface_name in the hw_inventory.json
      # sudo slcand -o -s6 -t hw -S 3000000 /dev/ttyUSBx
      # sudo ip link set up slcan0
      # For peak CAN adapters, only required to set baudrate
      # One sensor per interface for can, for ethernet we can use one interface/dev for multiple sensors
      master_inst_serial_type: "can_based"
      master_data_serial_type: "can_based"
      adapters:
          adapter_0:
              hw_type: "can"
              hw_dev_id: 2
              hw_iface_name: "can0"
              baudrate: 500000
