---
/**:
  ros__parameters:
# An array of sensors to subscribe to.
      sensors:
          # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
          # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
          sensor_0:
              # The model of the connected sensor. Available models umrr11, umrr9d, umrr96,
              # umrr9f_v1_1_1, umrr9f_v2_0_0
              link_type: "can"
              model: "umrr96_can"
              # The client_id of the sensor/source, must be a unique integer.
              id: 500
              # Adapter id to which sensor is connected
              dev_id: 2
              # The interface name of the sensor
              uifname: "umrr96_t153_automotive"
              # The major version of the interface
              uifmajorv: 1
              # The minor version of the interface
              uifminorv: 2
              # The pathc version of the interface
              uifpatchv: 2
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10